/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MetaPreviewRouteImport } from './routes/meta-preview'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaPreviewRoute = MetaPreviewRouteImport.update({
  id: '/meta-preview',
  path: '/meta-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/meta-preview': typeof MetaPreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/providers': typeof ProvidersRoute
  '/screening': typeof ScreeningRoute
  '/support': typeof SupportRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/meta-preview': typeof MetaPreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/providers': typeof ProvidersRoute
  '/screening': typeof ScreeningRoute
  '/support': typeof SupportRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkin': typeof CheckinRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/meta-preview': typeof MetaPreviewRoute
  '/onboarding': typeof OnboardingRoute
  '/providers': typeof ProvidersRoute
  '/screening': typeof ScreeningRoute
  '/support': typeof SupportRoute
  '/symptoms': typeof SymptomsRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/education'
    | '/meta-preview'
    | '/onboarding'
    | '/providers'
    | '/screening'
    | '/support'
    | '/symptoms'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/education'
    | '/meta-preview'
    | '/onboarding'
    | '/providers'
    | '/screening'
    | '/support'
    | '/symptoms'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/checkin'
    | '/dashboard'
    | '/education'
    | '/meta-preview'
    | '/onboarding'
    | '/providers'
    | '/screening'
    | '/support'
    | '/symptoms'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckinRoute: typeof CheckinRoute
  DashboardRoute: typeof DashboardRoute
  EducationRoute: typeof EducationRoute
  MetaPreviewRoute: typeof MetaPreviewRoute
  OnboardingRoute: typeof OnboardingRoute
  ProvidersRoute: typeof ProvidersRoute
  ScreeningRoute: typeof ScreeningRoute
  SupportRoute: typeof SupportRoute
  SymptomsRoute: typeof SymptomsRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-preview': {
      id: '/meta-preview'
      path: '/meta-preview'
      fullPath: '/meta-preview'
      preLoaderRoute: typeof MetaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckinRoute: CheckinRoute,
  DashboardRoute: DashboardRoute,
  EducationRoute: EducationRoute,
  MetaPreviewRoute: MetaPreviewRoute,
  OnboardingRoute: OnboardingRoute,
  ProvidersRoute: ProvidersRoute,
  ScreeningRoute: ScreeningRoute,
  SupportRoute: SupportRoute,
  SymptomsRoute: SymptomsRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
